services:
    - redis
language: python
python:
    - 3.8
    - 3.7
    - 3.6
    - 3.5

install: pip install -U tox-travis
script: tox

deploy:
    -   provider: pypi
        distributions: sdist bdist_wheel
        user: bogdandm
        password:
            secure: AgtI6R5crB9FXV3MeKNeRrnQ3iPuJJJ57LaVcMr4DjOwuz3IMVdbiPBrG8d4Rk9U6gjd6MDwlpmv0yDGLibbwvWmbcUTxyO3DSly2P3+D/uqVcxp6U/pgdnM9e7kcPwTfqcBmpg6lr/9kG0C2hOkUAsF8oUGCshGskc9bNXtGRoU1ZEY6FtmE9TD5F1qm3w6ZP9QHTHikInflPGkERvwddBA5v0quWvj8GqlKL7MBvlQZIq52R7u9MLcLPbXYSqftVKV1nYa9YKkRyXT4JEpeUKW/xRQJ9UBhTJTJZdoB8jJukNt29v/jr13xWYtwk8xtgAhhmgBBl/v4a1VnwC4kLfcVuUePiktDJZJEVQaHggHP/NhH5eaVYjdoxjyTpC212x5iAOaJVLTK/m6ua1aAhQaknzaDIXOBgJv24rYH+W2mavz5vAY+TwKQciE2j4y3TINTzhrbpkAdL5TAWS+qJIaIVNCMidae/Kl1B3dehJt+YvTYkZcGZ5DWxZRrMYpzVHOdoSCLyT/CF5pF/nTYyJxEF4D7IqPSgkW5ej+8AXHEexRxdXWTP3hYZlhT5TmulXhryoj4ROw3fGzoqBChIz/Lrv/9j8GJqe9OoQFRb5u856Uae0K/WOrXuvk91BCSLr4iC3/MbjRpWlgdcjr5dGKdFiVt2I0J9kT48GmBWs=
        on:
            tags: true
            all_branches: false
            repo: bogdandm/redis_bulk_cleaner
            python: 3.8
        skip_existing: true

#    -   provider: releases
#        api_key:
#            secure: PLEASE_REPLACE_ME
#        file_glob: true
#        file: dist/*
#        skip_cleanup: true
#        overwrite: true
#        draft: true
#        name: ${TRAVIS_TAG} (draft)
#        on:
#            tags: true
#            all_branches: false
#            repo: bogdandm/redis_bulk_cleaner
#            python: 3.8

