services:
    - redis
language: python
python:
    - 3.8
    - 3.7
    - 3.6
    - 3.5

install: pip install -U tox-travis
script: tox

deploy:
    -   provider: pypi
        distributions: sdist bdist_wheel
        user: bogdandm
        password:
            secure: Asn12i7DSbKCwOiSs6JoaXDff3FvqRsn8myZtVSzsPHbvg7i0Vgsn55u/3xvqM0aXJYFF1MhHHkoumPVE10gHXfAIA5i6f2vAtym/8CA/UbEhLesH0pKo4DH3eXdOFxtA22dMCDx6/wL/rPC0+O5TxCxD29ZzDGMRDvC/gR4R//QBCY9j0G+eYxdm3xMr73jo8FBeOSdVrfqQahfon+TCinIjmQdGyQW9OLpUUtfw6aqFdlU55uppYaIQxc4LTVC5PEYxRYh7NDJLobo/lWhPQs//s3gl8XjUBk8ce0BY8ofC/YPKIIKpipN5NO6sB6vPHRL3Xntyp61aaHBl4beFXHTxKRG5SYQ1HF8OpUu4QwKaQkWJpkyOuespdxbtQOeptL4+6oRNJbU3yQvlBhbz+MvMC0OwPQ4T0cnMvXPyGZYH1DoWGMr+C38X/vAzoNg2B8DDgaX6AdltG5NCE7HVzhi8A9f55tqsy5IdRsZA+sWvfdOCngwQ4uIhA4+3KaIFBMHJidvDpkqytWtZ6FPKNmErKYJNA3spugFnjUf3KwtgA2SDfTT2BmJ1wbyyyrosNryn9yv0I4/17inVHHGyuVTM5VinS3fyQt8iEKsIf9tbQsgLab68XNBQZGQsXyGn7CTPJKyPMDO9n21ysBFl9Wkj8TwHmrMsk/ipXjwjEc=
        on:
            tags: true
            all_branches: false
            repo: bogdandm/redis_bulk_cleaner
            python: 3.8
        skip_existing: true

#    -   provider: releases
#        api_key:
#            secure: PLEASE_REPLACE_ME
#        file_glob: true
#        file: dist/*
#        skip_cleanup: true
#        overwrite: true
#        draft: true
#        name: ${TRAVIS_TAG} (draft)
#        on:
#            tags: true
#            all_branches: false
#            repo: bogdandm/redis_bulk_cleaner
#            python: 3.8

