language: python
python:
    - 3.8
    - 3.7
    - 3.6
    - 3.5

install: pip install -U tox-travis
before_script: sudo service redis start
script: tox

deploy:
    -   provider: pypi
        distributions: sdist bdist_wheel
        user: bogdandm
        password:
            secure: PLEASE_REPLACE_ME
        on:
            tags: true
            all_branches: false
            repo: bogdandm/redis_bulk_cleaner
            python: 3.8
        skip_existing: true

    -   provider: releases
        api_key:
            secure: PLEASE_REPLACE_ME
        file_glob: true
        file: dist/*
        skip_cleanup: true
        overwrite: true
        draft: true
        name: ${TRAVIS_TAG} (draft)
        on:
            tags: true
            all_branches: false
            repo: bogdandm/redis_bulk_cleaner
            python: 3.8

